version: '3.7'
services:
    laravel.test:
        build:
            context: ./docker/8.1
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: raweb-8.1/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${PHP_PORT:-80}:80'
            - '${OCTANE_PORT:-8888}:8888'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        volumes:
            - '.:/var/www/html'
        networks:
            - raweb
        depends_on:
            - mysql
            - redis
#            - meilisearch
            - minio
    nginx:
        image: nginx:1.18
        ports:
            - '${APP_PORT:-8080}:80'
        volumes:
            - .:/var/www/html
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./docker/nginx/sites-enabled:/etc/nginx/sites-enabled:ro
            - ./docker/nginx/logs:/var/log/nginx
        networks:
            - raweb
        depends_on:
            - laravel.test
    mysql:
        image: mysql:8 # https://github.com/docker-library/mysql/blob/696fc899126ae00771b5d87bdadae836e704ae7d/8.0/Dockerfile
        environment:
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD:-secret}'
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD:-secret}'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        volumes:
            - mysql-data:/var/lib/mysql # https://github.com/docker-library/mysql/blob/696fc899126ae00771b5d87bdadae836e704ae7d/8.0/Dockerfile#L67
            - ./database:/docker-entrypoint-initdb.d/
            - ./docker/mysql/mysql.cnf:/etc/mysql/conf.d/mysql.cnf:ro
        networks:
            - raweb
        command:
            - "--default-authentication-plugin=mysql_native_password"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin # https://github.com/phpmyadmin/docker/blob/master/fpm-alpine/Dockerfile
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: mysql
            PMA_USER: '${DB_USERNAME}'
            PMA_PASSWORD: '${DB_PASSWORD}'
            PMA_PORT: 3306
        ports:
            - '${FORWARD_PHPMYADMIN_PORT:-8081}:80'
        networks:
            - raweb
    mailhog:
        image: 'mailhog/mailhog:latest'
        ports:
            - '${FORWARD_MAILHOG_PORT:-1025}:1025'
            - '${FORWARD_MAILHOG_DASHBOARD_PORT:-8025}:8025'
        networks:
            - raweb
    minio:
        image: 'minio/minio:latest'
        ports:
            - '${FORWARD_MINIO_PORT:-9000}:9000'
            - '${FORWARD_MINIO_CONSOLE_PORT:-8900}:8900'
        environment:
            MINIO_ROOT_USER: 'retroachievements'
            MINIO_ROOT_PASSWORD: 'retroachievements'
        volumes:
            - 'minio-data:/data'
        networks:
            - raweb
        command: minio server /data/minio --console-address ":8900"
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
            retries: 3
            timeout: 5s
    redis:
        image: 'redis:alpine'
        ports:
            - '${FORWARD_REDIS_PORT:-6379}:6379'
        volumes:
            - 'redis-data:/data'
        networks:
            - raweb
        healthcheck:
            test: ["CMD", "redis-cli", "ping"]
            retries: 3
            timeout: 5s
networks:
    raweb:
        driver: bridge
volumes:
    mysql-data:
        driver: local
    minio-data:
        driver: local
    redis-data:
        driver: local
